# Generated by Django 2.2.7 on 2019-12-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_pic',
            new_name='profile_pic',
        ),
    ]
