# Generated by Django 2.2.7 on 2019-12-15 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_auto_20191209_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('currency_name', models.CharField(max_length=50)),
                ('currency_value', models.CharField(max_length=50)),
                ('realse_date_ad', models.IntegerField()),
                ('realse_date_ah', models.IntegerField()),
                ('km', models.IntegerField(blank=True, null=True)),
                ('metal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('usa_price', models.FloatField()),
                ('catalog_price', models.FloatField(blank=True, null=True)),
                ('pick_number', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.Category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.Country')),
            ],
        ),
    ]
