# Generated by Django 2.2.7 on 2019-12-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_category_coins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coins',
            new_name='Coin',
        ),
    ]
