# Generated by Django 2.2.7 on 2019-12-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0009_auto_20191215_0900'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
