# Generated by Django 2.2.7 on 2019-12-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0010_auto_20191215_0904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.AlterModelTable(
            name='categories',
            table=None,
        ),
    ]
