# Generated by Django 2.2.7 on 2019-12-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0012_auto_20191215_0917'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
    ]
