# Generated by Django 2.2.7 on 2019-12-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0014_auto_20191215_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='km',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
