# Generated by Django 2.2.7 on 2019-12-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0015_auto_20191215_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='realse_date_ad',
            new_name='realse_year_ad',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='realse_date_ah',
            new_name='realse_year_ah',
        ),
    ]
