# Generated by Django 2.2.7 on 2019-12-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0016_auto_20191215_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
