# Generated by Django 2.2.7 on 2019-12-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0017_auto_20191217_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='rank',
        ),
    ]
