# Generated by Django 2.2.7 on 2019-12-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0018_remove_coin_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='realse_year_ad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coin',
            name='realse_year_ah',
            field=models.CharField(max_length=50),
        ),
    ]
