# Generated by Django 2.2.7 on 2019-12-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0019_auto_20191218_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='Print_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
