# Generated by Django 2.2.7 on 2019-12-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0020_coin_print_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='Print_city',
            new_name='print_city',
        ),
    ]
