# Generated by Django 2.2.7 on 2019-12-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0021_auto_20191222_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
