# Generated by Django 2.2.7 on 2019-12-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0023_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='rank',
        ),
    ]
