# Generated by Django 2.2.7 on 2020-01-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0024_remove_coin_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
